(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.Yes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		playSound("yeswav");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#367853").ss(4,1,1).p("ACWhjIjHDHIhkhk");
	this.shape.setTransform(-0.9,1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#187752").s().p("AiwA9QhJhIAAhoIAAgSQAGBbBDBBQBJBKBnAAQBoAABJhKQBDhBAGhbIAAASQAABohJBIQhJBJhoAAQhnAAhJhJg");
	this.shape_1.setTransform(-1.1,15.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#36BC88").s().p("AiwCwQhDhCgGhbIAAgTQAAhnBJhJQBJhJBnAAQBoAABJBJIAGAFQBDBIAABjIAAATQgGBbhDBCQhJBKhoAAQhnAAhJhKgAgvBxIDHjGIjHDGIhkhjg");
	this.shape_2.setTransform(-1.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.1,-25,50.1,53.8);


(lib.Photos = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(7));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("ADHSzQAFgeAOgbQgEg4AagyIAcg1IAAgTIAAgTQAfhHAThOQAJgnAQglIAAgJIAAgJIADgJIAJgTQgBgKgDgJIgIgTQgBg1gSgyQgJgbADgdQgQgVgCgaQgBgTgGgTIgKgJIgJgJQgIgNgDgPQgDgKgFgJIAAgKIAAgJQgWgZgLgfQgFgOABgOQgNgVgLgXIgYAbQgQARgIAWQgIAEgGAGQgIAIgGAKIgKAIQgLAGgLAEIgIAKQgEAEgCAFIgEAKQgKAEgIAGQgMAIgKAKIgfAIQgoAKgmATQicgNiXgmQhlDChLDVQgiBhgbBkQADAdgKAcQgHAUgLARQABAhACAgQABAWgNAQQgjgNAKg1QADgXAAgYQAJgSAIgTIAIgTQAukbCKj9QAeg2AigvQhagYhZgiIgZgLIgGgJIgNgTIgGgJIgHgFQgPgFgPgDIgKgJQgkgfgXgpQgKgTgGgWIgSgTQg7hCgfhTQgNgjgXgeQgBgFgBgFQgJg8gCg9QgCgqAAgrIADgJQAFgJADgKQABgEAAgFQACgFACgEIAOgUIAKgSQBBg4BDg4IDXizIAGgJQAbgqAtgYIAggSIACgKIADgJQBrg8B4gfQBegZBcgPIDBADQADADAEACQAIAEAKADIAKAJQAfAYATAiQAKARACAUIAHAIQATAQAHAXIAHAcQACAEADADQAQARAIAWQAIASgCAUIAEAKQASA0AVA0QAPAmgSAjQgIAAgEgEQgNgMACgVQABgOABgOIgHgKIgGgJQAAgFgCgEIgXg4QgLgbgCgeQgBgFgDgDQgNgTgLgUIgJgSIAAgKIAAgJIgHgJIgSgTIgKgKIgCgJIgBgJIAAgKIgDgJIgGgKIgGgJIgNgJIgSgKIgJgKIgEgFQgLgDgKgFQgDgCgBgDQkVgCkEBpQgHAFgHAGIgOARIgJAKIgQAIQgwAYgeArIgGAJIiGBxQhqBahrBYIgDAJQgMASgHAUQgGAPgJANIAAAJQAAAvAFAuIAHBVQABAFACADQAbAtAWAwQAOAcAKAeIAJAJQAUAYAYAXIASASIACAKIACAJIACAKIAGAJQAQAXANAXQAJAPANALIADACIAcAHIALAKIARASIAJAKQBmAsBpAkQAbgkAdggQgVAlgUAlIBGAWQBuAjBygPIATgJQApgSAqgLIAJgJQAYgaAegVIAMgJIAFgKIAEgJIANgKQAjgiAdgnQgBgHAIgCIARgeQADgFAEgCQBNgrA+g+IAKgJQANgEAOgGQAVgKAOgRIAsgKQBAgNAqgxQAAgFACgEQAEgOAAgPIAAgSIAHgKQAQgaABgeQABgcAAgcIgDgJQgMgXgGgZQgGgWACgYIgFgKIgPgcIgIgTIgJgJIgJgJIgDgKIgEgJIgGgJQgIgKgGgKQgBgEAAgFQABgEACgBQAMgEANAAIAIAKQAfAyAcA0QAQAegFAkIACAKIAIASQAFAKAGAJIACAJIABAmIAAAvIgDAJQgJANgEAPIgIATIgBAJQgCATgFATIgIAcIgMAKQgPAMgKAQIgEAGIgJADIhwAfQgFAFgGADQgVAKgVAJIgKAKQg4A2hCAnIgPAKIgHAJIgOAWQAhA3AcA4QAOAbgBAfQAYAoATAsQAIASgCATIAbBxQAIAgADAiIAEAJIAJATQgSBpgeBoQgPAzgZAxQgKA/gdA8QgOAeADAiQgcArAEAzQABAdgFAbQgBAFgDACQgJAEgJACQgNg3ANg5gAo6IHQgCgJAAgJIgGgJIgGgKIAAgJIAAgKIgGgJIgKgTQh/hIiWgZQgEgBgDgFQAcggAjgbQAJgGAGgKIATgJQAIgJAGgLQAGgMAMgCQAIABAJAEQAEACADAFQgIAbgaAUQgPAMgNAQIgTAJQCIAcBrBxQAVAXAIAhQgBAFgEADQgJAIgLAGIgFgKgAITGnIgCgFQCPgGCTg8QAdgMAhgFIgXgGIgxgMIgJgKIgIgIIgLgLIgKgJIgFgKQgGgPgIgOQgLgSgIgTQgGgNgDgOIgGgJIgGgKIgHgJQABhWARhVQAXh8ATh9QAdjTASjUQADggAAghIgGgKIgGgJIAAgJIAAgKIAAgJIAAgTIAAgJIgHgKQgLgUgMgSIgZglQgHgJgEgJIgWgKIgTgJIgGgJIgGgKIgGgJQgKgFgIgGQhphXh5g/QhGgmhEgqQmJh6lnC2QgnAUghAgQhDA+hDA9IgGAJQgKAOgLAMQgWAWgZASIgKAJQgCAFgDADQg6A9gDBRQgDBZAHBYQACAugZAbQgHgIgBgIQgHhZgFhZQgFiPBqhiQASgRAUgOIAGgJIAHgJIAGgKIAGgJQAngUAagjQCHivDYgmQA4gKAvgKQFohAEfDFQAsAeAtAgICABdIAJAKIAHAJIAGAJQAEADAGACIAVAHQAGAFAFAGIAeArIAZAmQAJAPAGAPIADAKIAAAJIAAAJIAAATIAAAJQAWBRgQBXQgvEAgREFQgHB2gjBzQABAFACADQAQAVAGAcQADATANASQAMASAKATQAIAFAHAGQAEADADAFIADAGIAAACQAoAIAkAQQAMAGAJAJIACAJIgCAKIgEAIIgIALIgDAGIgKACQhSAVhSAXQgiAJgeAQIgKAGQghAOgaAAQgpAAgYgjgAkTClQgIgOgJgNQgQgVgUgRIgCgTIgBgcIAAgcIAQgTQAQgQAVgIIAFgKIAFgJIAFgJQAPgKAPgHQAOgIAJgLQACgDAFgCQAsAGAeAgQAMAMAOAJQAQAagEAdQgHAwghAlQgZAZghAOQgQAGgOAIIg4AAgAjLgrIgTAKIgQAJQgNAXgKAYQgLAbgTAPQgOALAQATQAMAOAOAMQAEAFAEABQANAEAOAAQA8gZAmgzQAKgNABgOQgFgigcgaQgQgOgTAAQgIAAgIADgAmTjtIgIgcIgIgTQAAgqgDgqQgDgfAdADQAPAjgEAoQgCAOAAAOQAMAXAHAYQACAJAAAKQgHAEgHAAQgMAAgLgOgAAskyIgBglQgQgfgDgiQgBgSgOgLQgGgSAFgTQADgPARAFIAIAUIABAIQATAaAEAfQACAOAAAOQAPAVgCAaIgBAcQAMAXADAYQABAHgGAIQgngWgBgyg");
	this.shape.setTransform(14.2,18);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AKKRWQgEgBgDgEQgNlngclrQgJhoAQhVIgZARQj5APjygnQhKChhXCoQgmBIgfBMQACATgGASIgIATIAAATIAAAJIgJATIgEAJIAAAdIAAASIgJATIgDAJIgBATIgDATIgVAMQgLgQADgVQABgOAAgOIAHgKIAGgJIAAgcIAAgcIAGgKIAGgJIAAgTIAAgJIAJgTIAEgJQBBjSBsjFQAdg2AlgqQgxgIgvgLIgJgJIgcgcQgTgRgOgWIgEgIQhAgngvg1QhZhjgZiAQgPhNAVhIIAAgJIAAgcQABgUAHgSQAIgTAJgSIAAgKQAAgOAGgOQAJgSAGgUQAEgMAAgMIAAAAQhkAHhkAFQgDAFgCAFQgGAUgLARIgGAJQgDAYgIAXQgUAygRA1QglBzgGB4IgDAJIgJATIAAAJIAAAmIAAAJQAABBgDBBQAAAKgDAJQgFADgFABQhIAFhBgcIgTgJIgTgJIgCgKIgBgcIAAgJIgEgIIgPgdQgBgDgDgBQgKgFgLgDQgDgFgEgEQgKgKgLgJIgCgKQgBgMACgNQgFgDgDgFQgFgHgBgKIAAgJIAAgKIAAgJIAGgJIAGgKIAAgJIAAgJQAcg6AMg+QAfivA8ioQBGjCCxhdIDbADIAWAJQA8AbBEgCQADAAADAKQgBADgDAAQhFAVhAgcIgWgJIjhADQgKAFgIAGQgtAggnAoQgQARgLAWIgGAJIgrBCQgIAsgUAoQgTAlgNAnQg5C1gmC5QgEAUgNAQIAAAKIgBAJQgBAIgDAGIAGACQANAJgCAQIAQAJQASAJAQANQAFAFADAFIARAlIAAAJIAAASIAAAJQAFAFAGADQAkAWApAEQAWACAWgBIAAgKIAAglIgBgIQgEhIANhFQABgFADgEQAAgYACgXQADg1AQg0IBDjpQABgEADgEQAQgQAFgWIADgKQAIgZARgJQBnABBmALQACAAACADIAAgDIAGgJIAohKQAeg1Afg0QAFgJADgJIAKgJIAbgeQASgWAQgYIALgSIAWgTQA0grAwgyQAvgwA9gSQDAgiCeBZQBAAkAqA7IAPAJQAVAOAVANQATAMAPARQADADADABIA0AMQAEACACAFQABAEAAAFIgEAFQgEACgEAAIg8gBIgIgKQgRgUgUgPQgZgSgegMIgJgKIgGgJIgHgJIgGgKQgtgegvgaQimhXjAA1QgHAEgHAGQglAfgiAkQgjAkgpAbIgHAJQgOATgLATQgVAfgcAaIgKAJIgDAJIgDAKIgDAJIgDAJQgKAKgGALQgYAogVApIAOgLQBZhEBjgmQAbABAZAJQAGACADAKQhgAThXA4QgvAfgfAsIgNAJIgJAJIgBAJQgFASgQALIgDAAIgJAgQgEANAAAOIgEAJIgGAJIgIALIgEAJIgCAJIgBAJIAAAKIAAASIAAATIgEAJIgFAKIgDAJIAAAKIgBAvQgCAmAJAkIAJAvIAGAKIAUAbQALAOAGAPIAKAcIAKAJQAcAYAXAbQAnAuA1AiIAEAJQAGAJAHAJIAbAdIATATQA4AOA5ALIARgQIgIARQDkApDsgRIAPgKIAjgaIAGgRIABAMIAJgGIA+gvQACgFADgEQAOgVAQgTQAYgeAUggIAMgTQACgFAAgFIABgJIAHgJIAIgKIAHgJIACgKIACgJIADgJQAEgKAFgJIAMgTIAAgJIAAhLIAAhxIAAg4IgEgJIgFgKIgEgJIgGgJIgGgKIAAgJIAAgJIAAgKIgEgIQgagogMguQgRg+gig0QgJgNgKgNIAAgJIAAgKIgHgJQgDgFgBgFQAAgEABgFQACgDACgCQAEgDAFAAQAJAAAJACQAFAJADAKQAQAxAWAwQAcA+AfA/IAOAfIADAJIAAAJIAAAKQAIATAEAUQASBRACBWQADBPgdBGQgHASgCAUIgGAKQgVAggSAiQgcA4gtAuIgHAJQgEAFgGADIhBAzIgQAMQATFEAEFHQACCDAQB6QAJAbgZAAIgFAAgAD5AOQgnglgdguIgNgTIgTgJIgOgUIgEgIIAigKQAoAgAYAsQAFAJADAJQAcAXAiAOIBVgDQARgKALgSIAGgJIAAgKIAAgSIAEgJIAJgKQgGgcAPgVQAIgMARAFQANAMgHAQIgJATQACAOgGANIgJATIAAAKIAAATQgKAVgUAQQgHAHgGAIQgcAFgbAAQg0AAgygSgABBmnQADgSAAgTIAJgTIAEgJQAAgvgEguQgDggAdADQAPA2gCA7QgBAagQAVQAAAlACAmQAAAQgLAMQgjgSAKg6gAIUm5IgBgJIgHgKIgGgJQAAhVgHhTQgFgxAigLQAQBIgFBOQgCAcAAAcQANARgBAUIgCATIgWANIgFgTgAAUsfIACgEQAGgFAGAAQD6gLD5gQQBEgEA6gYQAJACAGAFQAHAGADAJQhNAlhWAEQiDAHiDAAQh4AAh3gGg");
	this.shape_1.setTransform(-12.4,47);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AjySUQDEl1CmmEQA1h8A/hmQj3AVj0ArQhsDmjFCzQg9A4gVBTQgKApghAGQAtjTCyiRQAwgoAfg2QAphIArhCIhcASQiTAeiEgsQgYjwAgjvQAajBAoi9QAqjHA+jDQADgEAFgDIALgHIADgFIAEgJIAAgJIAAgKQAQgpAKgrQAJgpAegPQAQABAPAFQAHACAGAEQAOAagCAfQgDAfAAAfQBRgLBPARIACATIABAlIAAAKQA0hBBChIQAXgZAPgdIBTgJQASAJAIARQALAXgCAaQAJANAFAOQAJAaACAcQAEgBAEgDQARgQAWgLIAFgKIAKgSIADgKIAXgRQATgMAPgRQAcgCAbACQAHABAGAFIAUBwQAEAcgBAdIgBAcIAPgLIAmgkIADgKIADgJIAcgcQAQgRAWgIQAbAAAaAEQADABADAEQABAsAIAqQAHAkADAlIADABQAhhFAfhJQAIgSAGgTQAFgPALgNQAFgEAFgBQAMgBAMADQAGBPgBBRIgCCBQAOATACAbQAXEwgyEpQgTBzgwBrIgTATQhAA5hPAiQhVAEhUAHQgDBAgoA9QgSAcgUAaQiCEniEEoQgzBwhDBnQgKAOgJAAQgIAAgIgLgApAoAQg3FggQFmIgBAcQCxAdC5gQQAmg4ApgzQgTA1gXAyQBSgJBUgSQDJgrDMgVQEtggAKkvQAFiJAQiIQARiWgbiOIgFACQgFgbgCgdIAAAAIgKgJIgogdIgfgIIgEARQgIAcgWATQgfgXACg1QgkgGgngBQgSgBgTgDIgKgJIgJgHIgGgBIgFAAIgBAEQgFACgFAAQgRAAgRgCIgBgEIgYABIgSAKIgNAJIgFAKQgIAVgSAMQgFAEgIAAQgDgFAAgEQABgVALgRIAKgTQADgEAEgDQAYgPAZgMIARAAIAAgTQACghAAghQgJgMgBgQQgDgcAAgcQAAgFgBAAQgQgEgRAAIgKAIIgbAUIgGAJQgJAOgHAPIgDAJIgQAKIgZASIgGAKIgFAIIgIAKQgFAFgFABQgNADgOAAQgGgugLgvQgKgngOgkQgCgFgCAAQgagFgZAAQg6BOg+BHIgbAgQApATAoAaQBJAuA8A4QgBAFgDABQgOAFgQACQhYhUhug0IgHALQgFAFgFACQgKAEgLABQgKgQABgVIABgGQhrgohyAPIgCAKQgEAggLAfQgBAFgGADQgNgGgFgKQg+DIghDQgAJkvTQgMAegVAaIgCAKIgBAJIAAAJIgEAJIgOATQAlAQAkAVQgCgkACgmQABghAAghIAAg4QgKAVgKAagAHDv8IhOBSIgNAPQBEAJA/AVQAEgdAAgdIAAgJIgEgJIgFgKIgEgKIAAgJIAAgJIAAgKIAAgDIgPgBIgQABgAliv6QBGAHBDAWIAAgVQgtgJg5AAIgjABgAl2v7QgJgZACgdQACgkAAgkIAAgBIgTABIgGATQgHAYgMAXIgLA6IAQAAIAsACgAjTBrQgDgFAAgFQgDgNAAgOIAAgKIAEgJQAKgRAEgUQABgFADgFQAshQBDhAQADgDAFgCQCYACCYAKQAEABADAJQAAABgBAAQAAABgBAAQAAABAAAAQgBAAAAAAQibAIiZAFQgFAEgDAGQgFAIgDAKIgJAJIgmAmIgJAJIgDAJQgIATgKASIgDAJQgCAUgMASQAAAAAAABQAAABAAAAQAAABABAAQAAAAAAAAQB6AmB4gjQADgDAEgCQARgGARgFIAKgIQAPgLAPgJIAGgKQAJgUAPgRIAGgHIAVgdIAAgKIAAgJQADgFADAAQARAAARAFQAAAFgCADQgLASgKAUIgHALIgqBAQgEAFgGADQgZAPgVAVIgJACIgZAHIgKAJIgGAHIgJACQgmACgkAAQheAAhbgRgAlvmOQAAgxAjgHQAQBaACBhQAAApgZAWQgbhXgBhrgAD4nrQgCgrAhgIQAQA/gDBFQgBAcgGAcIgWAMQgKhIgFhNgAgWt4QgCgBAAgJQAAgDACgCQAEgDAFgBQBsABBsALQAEAAAEAKQgBAAAAABQgBABAAAAQgBAAAAABQAAAAgBAAIg6AAQhWAAhVgGg");
	this.shape_2.setTransform(14.9,47.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("Al0WmQgCgOAGgNIAJgTQgBgfAQgaIAKgSQCNl+B0mMQAniIAzhqQjMgkjEhmQhGgmhMgXQgSgGgSgJQgFghAAghQAAghAIgfQACgKAFgJQARhVAUhTQAVhWAjhUQAJgWAUgPQAfhAAsg6QAsg4AYhCIANgJIAZgTIAGgKIADgJQAXgRAbgMIAfgPQCCgECAgKQACAAACgEQADgFAAgFQABgOAHgNQAEgJAHgBIAfADIAVATQASATAUAPQABAAAAAAQAAABABAAQAAAAABAAQAAABABAAQASAEATADIAFAKQABAEAAAFIAAAJQDWCQDCCoQBZBNgsBsQgvCKgrCPQgyCpiQBmQgxAHgwAEQAPD0geD2QgMBogEBoIgJATIgEAKQAFArgLAqQgEASgSAGQgGieAbizQAhjTgRjZQgDgoAHgdQiMAHiIgXQgeCyg9C6QhvFPh5FGQgOAbgIAeQgDAIAAAKIgJATIgHASQgLAHgLABIgBAAQgCAAgDgFgAimrdIglATIgQAJQgGAJgHAJQgPAQgSANQiDDBhNDYQgdBPgQBVQgGAdgQAaIAAAcIAAAuIAAASQE5CJFaBUQBdAWBcgGQAIgSAMgMIACAcQAogEAngJQCih9AvjJQAVhdAnhWIAKgvQAIgggCghIAAgKQizjGjpiRQghgVgbgaIhxAAQgLAbgPAYQgSAdgYAXQgIAAgHgDQgEgCgBgFQgBgEACgFQAKgNAEgPQAGgXARgPIAKgJQhwgGhwgFIgHACgAr2ItQhAgchEgXIgHgJIgIgKIgEgJIgGgJIgGgKIAAgJIAAgKIAAgJIgEgJIgFgKIgEgJIAAgJIAAgKIAAgJIAAgKIAAgJIgDgJQgOgigYgbQgkgqgqgmIgEgKIgEgIIgGgLIgEgIIAAgKIAAgJIAAgJIgHgKIgGgJIAAgKIAAguIAAhwIAAgJQACgFADgEQAJgNADgPQAFgZAOgWQAKgSAHgUIAKgKQAOgOARgIQAggSAYgZIgEgJIgFgKIgDgJIAAgKQACgTgGgTQgNgoADgsIABgcQgNgQAAgVQABhGgDhHQgDg+ANg8QAGgYAMgWIAAgKIAAgJIAEgJQADgFAFgFIAKgJIADgKIADgJIAFgKIAFgIIAFgKIAKgJIALgLIAIgIIAJgKIAJgJIANgFQAMgEAMgGQAFgCAFgFQAAgJACgJQANhBAfg8QAXgrAOgwQAGgUALgSIAAgJQAAgVAMgRQAbgoAUgsIAEgJIAAgKIAAgJQABgFADgDIAKgMQAEgDADgFIAEgKIADgJQAGgDAHgBIBKgNIAAgCQBxgLBrAWQA0AKAmAkIACAJIAFASIAHAUQAGASgCATIABADQA4AHA1gTQAEgFAGgEQAXgQAagMQAfgNAVgZQAGgEAHgCIA3gSQAGgBAEgEQAFgBAFAAQBaAABbABQAEAFADAGQAPAbAWAVQAlAjATAvIAHAIIAOAMIAKAIQACAFAAAFIABAJIAGAJIAHAKIAGAJIAJAJQADAEAEAAQBnAGBnADIAMAKQAhAgAdAkQAiArAXAwIACAJQABAOAAAOIAAAvIAAA4QAAAFACAEQADAFAEAFIAKAJIAJAKIAKAJIAYAKIAQAJIAIAKIAGAIQADAFAFAFIAPAKIAWASIATATIADAJIAEAKIAJAJIAJAJIADAKIADAJIAAAJIAAAKQAKAMAAAQIAGCMQACAvgdAkQgOASgJAVIAoA/QA3BUAeBgQAMAkgBAoQgCAmAAAkIgEAJQgJANgHAPQgGANgFAPIgMAmIgKAKIgSASIgTATIgQAQQgdAEgdAKQhNAZgkBJIgWAvIAAAJIAAATIAAATIAAAcIgEAJIgGAKIgFAJIgEAJIgSALIgKAIQhmAFhlgBQgTgBgTgGIgHgJIgJgKQgGgEgHgDQgWgHgYgEIgJgKIgKgJIgJgKQgCgEAAgFIgBgJIAAgKIAAgJQAAgFgCgDQgDgGgFgEIgLgLQgDgEgBgFQADgEAEgBQATgEAUAEQAEABADAEIACAKIABAJIAAAKIAAAJIABAJIAFATQADADAEABQAaAFAbAEIAJAJIAJAJQAFAFAGADIAVALQAEADAFAAQBWACBWgCIAKgJIALgKIAHgJQADgFABgFQACgNAAgOIAAgdIAAglQALgOAIgQQA9h6CHgVQAGAAAEgFIAJgKIAEgJIADgJQAJgFAIgHQADgCACgFQAAgFACgDQAHgPAGgOQADgKAGgKIANgbIAAgKIAAgbIAAgcIAAglIgGgKIgGgJIgBgJIgDgTIgGgTQgFgPgKgNIgCgJIgLgdQgKgVgQgSQgLgMgKgOIgCgKIgBgJIgGgJIgMgTIgLgSQgKgNACgQQAAgFABgEQACgFADgEIAJgKIAKgJIAJgKIADgJIAEgJIAFgKIAEgJIAAgKIAAglIAAheIAAgcIgGgKIgEgJIgCgJIgCgJIgCgKQgDgFgEgDQgNgMgIgQQgMgagZgNIgQgJIgGgKIgEgIIgGgHIgGgDIgZgHIgJgJIgKgJQgEgFgGgDIgVgLQgDgFgBgFQgCgSAAgTIAAhUIAAgcIgDgKQgKgfgRgaQghgygvgoIgDgBIjagIIgHgJIgMgTIgNgTQgJgNgDgPIgNgJIgMgKIgEgJIgUgkQgagwgpgmQhUgChTAKQgmAFgmAJIgLAIIg8AnIg1AiQgSADgRABQgyAEgyABIgFgJIgBgJIAAgKIAAgJIAAgJIAAgTIgGgKIgFgJIgBgJIgKgKIgJgJQgugWg2gHQh0gQhzAdIgGAKQgMAWgKAYQgUAxgfAtIgCAKIgBAJIAAAJIgLAdQgaBGgjBEQgWApgCAuQgCATgFASQgDAFgEADQgPAJgPAIIgfAQIgHAJQgKAQgOANQgLAMgIAOQgFALgIAJQgMAvgFAwQgLBcAABeQAAA1AHAzQAFAlAAAlIAGAKIAEAJIACAKIABAJIABAJIAFATQACAFADACQALAKANAHQAJAGAGAHQAGAHADAJQAAAAgBABQAAABAAAAQgBABAAAAQAAAAgBAAQg8ABgyAdQgTAMgPARIgDAKQgGAPgIAPQgJASgFATQgGATgNARIAAAJIAAAmIAABTIAAAcQAEAFACAFQAEAJACAKQACAJAFAHQAIAOgCAQIAHAJIAcAcQAOANAKAQIAEAJIAHAIQAHAGAIAFIAMAJIAJAKIAEAJIAEAJIAIAKIACAJIABATIAAATIAAAcIAGAKIAEAJIACAJIABAJQAAAFABAEIAFAKQAsAoA7AZQCbBDCqgQQAKgFAIgGQAhgUAVgfQAbgoAngeIADgJIADgJIAEgJIAFgHQAFgBAFAAQAJAAAIAEQAFACADAEQAAAFgDADIgDAEQA6gCAyAaQAYAMAYgEQAGgEAEgHQANgTATAGQAEABAEAEQABAFgBAEQgCAKgHAIQgLAMgJAPIgJABQgXAAgYgBQgVgRgdgGQgrgJgmgTIgCgBIgBACIgDAJIgDAJQgFAFgGADQglAWgWAlQgdAxgzAZQgoAFgoAAQh5AAhygzgAC0BSQgtgEgsgLQgBAAAAgFQAAgEABgEQACgGAEgCQAHgCAIAAQADADADAAQAfABAfgBIATgKQAUgNAYgCIAKgJIAegSIAGgKIAKgTIADgJIAAgJIAAgKIAAgJIAGgJIAHgKIAAgJIAAgmIAAgSQhggNhlAcIgWAHIAAAJQAAAvABAvQABATgFARQgCAFgDACQgIAEgJACQgDgFAAgFQgDg3gCg4QAAgYAFgXQADgFAEgCQA+gjBEgFQA8ACA7AFQAGABAHAFQADAEABAFQAHAqgEAqQgBAQgKAMIAAAKIAAAJIAAAKIgEAIQgJAOgGAOQgCAFgEAEQgEAFgGADQgZAQgVAUIgJACQgfAEgWATIgIABIgCAAgAh8lqQACgJAAgJIAUglIAFgKQAAgcAEgcQACgPAQAFQAXAwgTAxQgHASgNARQAAAOgEAMQgDAJgIAIQgXgNAFgfgAFlnpQgCgmAggDQAPAwgDA3QgBAYgFAXIgWAMQgLg6gDg/g");
	this.shape_3.setTransform(0.4,25.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#000000").s().p("AqVUcQGhjGDQmoQAvhhAYhqQAVhcgIhgQgLgRgGgTQgIgXgDgZQgVgjghgXQgJgGgEgFQhPAOhRgEQgqgQgegfQhDhFg7hJQgVgagYgVIgngjQhrhkgfiJQgjieBRiDQCcj8DviZQC8gUC2AtQBCAQA8AfQAxACAxAFIACgIIAAgJIAAgJIAMgTQAGgJAEgKQACgEAAgFIABgTIAHgJIAGgJIAAgTIAAgTIAAgJIAAgTQg3gLhAAVIgQAEQgbAHgTAUQgFAEgGACQgmAOAIgeQASgYAcgPIALgHQAygigQgzQgIgIgJgBQhPgLhPgFIgFgKIgCgGIAAgDQhgAPhUAtQhJAnhGAtQgsAGgmAVQgLAGgLAEIgrAQIgWgFIgKgEIgGAJIgGAJQgrAJgiAbIgPANQgXAUgaAQQgFAegKAcQgYBAgcBBQgVAygMA1IAAAmIABAJQAIAkgYARQgWgJAFgZIABgJQgEgnAMgkQABgFAEgFIAAgJIAAgTIAAgJQAHgUALgSIAEgJQAVguAOgvQACgGADgEIAAgKIAAgJQALgSADgTQAAgFADgEQAIgOADgPQAFgFAGgCQAUgKAHgVQAjgNAcgXQAFgEAHgCIAWgHIAOgLIARgSIAWgJIAMgGQCfgNCYhbIBbg4QAFgBAFAAQAfgBATgNIAfADIAMAKIAHAGICPAJIASALIAXARQAIASgCAUIAAAJQABAVgNAQICAAFQADAAADAFQAFASgBATIAAAKQADAigLAfIgFAKIAAAJIAAAJIgEAJIgPAdIgGAJIAAAKIgBAJIgBACIAcAEQAFAAADAKQgBAAAAABQgBABAAAAQAAAAgBABQAAAAgBAAIgpABQgKAJgLAIIgEAKIgDAJIgCAKQgQAQgLAUIgBABIADADIACAKIABAJIAAAJQABAFADAEQAHAKAIAJIAVATQAEAFACAFIAuBuQARAmAeAfQAMALAFAQIAKAIQAwAhApAqQAPAQAFAXIgDAJIgEAJIgGAKIgBAJQgPAygLA1QgIAogTAkQgFAJgCAJQgBAJAAAKIgEAJIgFAKIgEAJQhWBlhpBNQh0BXibAJQgQABgQAGQgpAOgpAJQClDTh2EGQjOHOmxDzQgYANgOAAQgRAAgEgSgAjMv1QhXA+hMBLQgvAvgjA3IhrCnQgNAUgUAPIgDAJQgVAyADA1QADAmAAAlIAAATIAAAcIADAJQAgA8ArAyQAeAiAcAkQADADABAFQAXAQASAVQBEBIBBBMQAVAZAYAXQARARAYAIQE+gOEUiPQAogWAigjQAjglAbgpQADgFAEgEQAHgGAHgEQACgFABgFQAGgsAQgqIAdhJIAAgJIAAgKIAEgIQAKgNABgQQACgOAEgOQAAgFgCgCQhMhDhAhLQgTgWgOgaQgJgTgMgTIAAgJIAAgJIgHgKIgGgJIAAgJIAAgKIgGgJIgGgKIgDgJIgTgJIgDgKIgDgJIgKgJIgJgKIgCgJQgBgKgDgIIgDgHIgFgKIgCgDIABgBIgBgFIAAgJIAHgJIAcgdIACgJQAEgOAIgMIhQABQhOgnhWgTQhegWhfAAQhNAAhOAOgAHwOrQACgTAAgTIAAgJQALgRAGgTQAHgYAEgYQB6j9glkjQgSiNh1hLQgGgSgRgNQgJgIAKgGIAJgDIATACQDTC/gkEqQgbDXhlDDIABAcQABAPgIAMQgEAFgGADQgTgFACgUgAAdjFQgCgDgCgCQgKgFgLgDQgggagkgVIgJgGQg3gFg0gNQgEgBgCgJQApgqBOAkIBdA3IAZANIBkgDQAVgQARgUQAJgLAJgJIADgJIADgKIATgSQAFgFAFgEIAJgEQAJACAIAEQAFACADAFIhKBcQgSAWgYAOIiDAAgAlaosQgCgmAfgDQAQAwgDA3QgBAYgGAXIgVAMQgLg6gDg/gAB+qWQgDgxAigLQAQBNgDBSQgBAigGAgIgWAMQgKhWgFhbg");
	this.shape_4.setTransform(-0.4,44.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#000000").s().p("AopTpIABgTQABgEAEgDQAHgHAKgEQAEgKAGgIQAHgKAIgKQABgUAJgSIASglQAljGAWjMQALhnAFhoIAGgJIAGgKQgCg6AMg5QAKgxAbgqQADgOAFgOIAHgTIAEgJIATgTQAEgFAGgDIAIgEQAKABAIAEQAEACADAFQgGAJgIAIQgGAGgIAFQgHAOgGAPQgFANgEAOIgGAKIgMASQgDA6gMA5QgJArgRAnQAAAhgHAfQgHAhACAjIgEAJIgJATQgICIgGCIQgEBPggBGQABAZgJAXQgMAbgIAdIgEAIQgIAKgKAKIgDAJIgDAJIgRAUQgHAJgEAJIgJABQgQAAACgUgAGxQVQABgcAAgdQgmhnABhwIAAhUIgJgTIgEgKIAAgJIAAgJQgzjWg/jTQgahZAlg0QALDHBIC8QAcBIALBLQAcDFAaDGQALBPgGBPIgWANQgKg/ADhEgAhuCmQhRgPhTgKQgkgFgkgKQgFgFgFgDQghgTgcgbQgSgRgIgXQgDgEgEgDQgKgHgLgEQgKgNgIgNQgcg1gZg3QgWgugagsIAAgvIAAh6IAAiNIAEgJIAFgKIADgJIACgJQAAgFACgEIAGgKIAHgJIAGgKIABgJQAAgYAIgXIgDADQgXgNAEgfQADggAAghIAEgJIAMgTIAEgTQAJgbgDgdIgBgKQACgEADgEQAKgNAAgQQgBgFACgEQASgYATgVIApgxQBmhABShXQAEgEACgFIAEgJIAPgJIAQgKIAGgJIADgJIAEgEQATgIAOgOQADgCABgEQAFgBAEABQANAEAMAGQACAFAAAEQACATAAATIAAASQCNguCag5QAWACAVAFQAEABADAFQAGAXgEAYQgFAlAQAcQAIAFAIAAQCRAICRADQBBA8gFBaIgBAJIAADhIgEAJQgDAFgFAFQAAAOgDANQgIAegOAbIAAAKIgBAJIgCAJQgDAFgDAAQgSAAgRgFQALgRAGgTQAIgdANgcIAAgKIAAgSIAAgKIAGgJIAGgKIAAiVIAAgKIAAhnIgFgKQgHgYgNgWIgGgKQiWgGiWgKQgIgBgIgEIgOgLQgHgIgHgKIAAgcIAAg+QiQAViIBPQgIADgIAAQgXABgXgBQgEgFAAgFQgDgSAAgTIAAgJQhTA4hTBNIgMALQg7Aug4AvQgCAFgDAEQgNAUgRASIgBAJQAAAQgKANQgDAEgBAFQACAYgEAXQgHAigQAfQAAATADASQACAPgCANQARgdAagYQAEgEADgFIACgJIABgJIAVgdQApg4A0gwQAcgZAbgbQAbgEAXgOQBQguBbgZIAAgBICDADIASAJQApAVAkAcIAUARIANAFIAWAHIAMAKQAgAdAoASIApASQADAFAEAEIAVAUIAfAcIAGAJIADAJIADAKIANAIIATAKIAIALIAKASIAKASIAMATIADAKIABAJIADAJIAFAKIAEAJIAAAJIAAATIAAATIAAAJQANAuAFAwQAJBYACBaQACBFgoA1IgDAJQgEAogYAfQgaAhgiAbIgDAKQgHAcgWASQgdAXgRAhIgNAJIgSAKQh8BvihAAQguAAgwgJgAhgvpQgoAOgnAPQgPAGgPADIg7AiQgQAKgTAGIg4A4IhCBCIgDAJIgDAJIgJAKIgKAJQgGAagSASQgWAVgJAcQgGAVgOARQAAAKgCAJQgDAOgGANQgEALgHAJIgCAJIgCAJIgIAUIgDAJIAABnIAACMIAAAvQAMAXAJAYQAJAZAOAUIAcAoQAFAXALAXQANAYAWAQQALAGAJAKIAEAJIADAJQAOAOAPANIAnAeIAHAGQEvBsEIiVQAcgcAggbQAcgZAWgfIACgKIABgJIAmgzQARgXAVgWQAHgHAEgJIAAgKIAAgJIAEgJQACgFAEgFIAIgKIAHgJIAAgJIAAgJIAAgKIAEgIIAJgLQAAhGgChGQgDhkgThhQgBgJAAgKIgXg4QgVgxg0gTQgHgCgHgFIgCgJIgBgKIAAgJIgJgKIgHgIQgJgJgJgHIgWgHQhLg1hOgyQgsgdgvgYIiCADgAiihNQgKgFgLgDQgdghgjgaQgKgHgIgJQAIgIAKgEQAHgCAKABQAhAhAkAWQAMAIAMAGIB9gDIAlgTIAMgGQAFgFACgFQADgJAAgJQAJgOAEgOQACgNANACIAAgCQAJACAIAEQAFACADAFQgHARgKAUQgGANgCAPIgEAJQgEAFgFAFQgJANgSAFQgNAEgNAGIinADQgCgDgCgBgAlNnEQgDAAgEgFQAAgJADgJQAEgKAGgKIAAgJIAAgJQAUgVAFgaQADgRATAEQAPAWgPAZIgNATIgDATIgDASQgIATgSAAIgIgBgACJpiQAAgmAgAAQAQA/AABFQABAegYANQgag6ABhPg");
	this.shape_5.setTransform(17.2,25.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AmrQ6IgGgTIgBgJIAHgJIAGgJIAAhCIAAgmIAPgTIAHgJQAYhpgGhuQgDgqAAgrIAHgJIAGgJIAAgmIAAgTIAGgJIAGgJQgBgjAMggQAFgOAJgNIAAgTIAAgTIAJgSIAEgKQAAhBgGhBQgEgnAgABQAYBrgWBtQgJAsgVAoQACATgHASIgIATQAAAXgCAXQgBAQgJANIAACpIAABKIgJATIgEAKIAAAJIAAAJQgFAQgJANQgGAJgFAJQAEA1gLAyQgGAdgXAAIgBgBgACeP3QgEgDgBgFIAAgJIAAgJIgJgKIgEgJQgHgigRgeQgFgLgIgJIAAgKIAAgJIgGgKIgHgJIAAgJIAAgTIgJgTIgDgJQgkj7gYj+QgIhUAWg7IgmARQg0AEgyAHQjEAciOiIIgEgJIgFgKIgHgJIgJgKIgIgKQgOgVgMgYIgBgEIgDADQgEADgFAAQgRAAgRgCQgDgFgEgDIgVgVIgNgPQgLgDgJgFQgFgCgDgFQgFgFgDgFQgGgNABgPIABgcIADgJIAFgKIAEgJIAAgJIAAgKIAEgJIAFgKIAEgJIAAgvIAAg4IAAheIgEgJIgFgKIgEgJIAAgJIAAgJIAAgKIAAgJIgEgJIgFgKIgEgJIgMgTIAAgJIAAgKIAAgJIgEgJIgFgKIgDgJIAAgKIAAgSIAAgdQANgaAWgWQAgggAkgbQAVgPAQgJQAtAFAuAAQAOABAIAEIAAAAIAFgKIAEgJIADgKIAKgJIAJgJIADgKIADgJIAKgJIAdgbQAUgSAQgVQAQgJAOgMQBFg3BDg6QAdgZAegKQBgACBgAGQAaACAZAGIAJAJIANAJIASAKIAEAJIAGAKIAPAKIANAJQABAEAEADQAmApArAlQAbAXAPAgQACAFAAAFIACAJIADAJIAJATIAAAJIAAAKIAAAJQAUBDgCBKQgGDAAADAIAAA4QAAAFACADQAKAOAGAQQAHATAKASIAGAKQAEAEAGADIAzAYQAMAGAOADIAKAJIAMAJIATAKIAJAKIAGAJIAHAJIASAKIAJAKIAIAHIAJAKQAMALADARQgCAFgDACQhWBChsAaQgEABgDADIgKADQh8AahYg8QgCgFABgEQABgFAEgCQAHgDAIAAQAEADAGACQBZAZBegOIAUgIQBBgYBAgcQAMgGALgJIgIgKIgGgHQgIgHgJgEIgJgJQgwgwg/gcQgigOgYgcIgCgKIgCgJIgCgKIgHgJIgIgKIgHgJIAAiMIAAmBIAAg4IgGgJIgHgKIAAgJIAAgJIAAgKQgVhXhFg4Qg3gug+ghQhig0iAAiQgLAEgIAIQgVASgYAOQgTAMgIATQgJAEgIAHQgiAdgkAZQgWARgTAVQgJAFgIAGQgVAPgMAWQgLAUgRAQIgBAJQAAAGgCAEIgFAKIgEAJIAAAJIAAAJIgBAKQgBAJgEAIQgEAFgGADQgGgDgDgFQgFgIgBgJIAAgcIAAAAQgygBgyABQgXAKgTARQgfAegeAfQgKAKgGAOIAAAKIAAAJIAAAJIAEAJIAFAKIADAJIAAAKIAAAJIAAAKIAGAJIAEAJIAGAKIAGAJIADAKIAAAJIAAAJIAAATQASAegCAkQgDAlAAAlIAABxIgEAJQgKARgHATQgGATACAUIAEAJQACAEAEACIASAHIAJAKIATASIAQAQQAJADAIAFIAEAEIAAgcIAAh6IAAjXQAHgOAEgPQAQg3AbgyQAxhaBFhMIADgKIAAgJIAHgJIAJgKIAJgJIAKgJIAHgFIALgGIAAgCQCJAHCIANQA1AFA3ADIASAKIAQAIIAVAMIAKAIIAJAKIAHAJIACAJIABAJIAAAKQACAEADAEQADADAFABIAPADIAGAKIAEAJIAFAKIAFAIIAFAKIAGAKIADAJIABAJIADAJIAFAKIAEAJIAAAmIAACyIAAD9IgEAJIgHALQgDADgCAFIgDAJIgFAKQgJATgFARIgDAKIgEAIIgIALIgJAJIgEAJIgDAKIgWASQgGAFgHAEQgcAQgeAOIgtAUQAUDpAXDrQAJBZAFBbIAJASIAEAKIAAAJIAAATIAIATIAEASQAcAsATAyQAFANgCAPQALAMgGAOQgCAFgGADQgNgHgKgKgAkZroIgJAJIgJAJQhHBrg8BxQgaAwgVAzIAADYIAACWQANAgAYAXQAMAMAHAQQE6DkEmkJQAEgYAMgWQALgSABgUIAEgIIAJgLIAAkGIAAiyQgMgWgIgXIgIgeQgGAxAFAzQAEAtgQAnQgkgnAJhTQAFgqAAgqIgDgJIgFgKIgEgJIAAgJIAAgKQidhEivAAQgyAAg0AGgAjAhgQgJgIgIgJQgEgFgGgDQgKgFgLgDQgRgSgIgWQgKgaAaAEQAnAhAlAiQAOANAQAKIAlAAQAngZAgghQANgNAHgTQAOAAAMADQAEABADAFIgJATIgDAJIgDAKQgXAdggATQgSALgOAQIhEADQgWgNgSgRgAk/k6QgCgDAAgGIAHgSIAFgKQAAgcAEgbQACgPAQAFQAQAigDApQgBASgPAKQgIALgIAAQgHAAgGgMgAgCmzQgBgfAcAAQAPAigDApQgBAUgFARIgWANQgKgtgBgxg");
	this.shape_6.setTransform(14.1,32.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-77.8,-113.4,183.9,262.9);


(lib.no = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_1 = function() {
		playSound("nopewav");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1).call(this.frame_1).wait(1));

	// Layer_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#A23636").ss(4,1,1).p("AAAAAIBkBkABkhjIhkBjAhjhjIBjBjIhjBk");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A23636").s().p("AiwA9QhJhIAAhoIAAgSQAGBbBDBBQBJBKBnAAQBoAABJhKQBDhBAGhbIAAASQAABohJBIQhJBJhoAAQhnAAhJhJg");
	this.shape_1.setTransform(-1.1,15.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#D86060").s().p("AiwCwQhDhCgGhbIAAgTQAAhnBJhJQBJhJBnAAQBoAABJBJQBJBJAABnIAAATQgGBbhDBCQhJBKhoAAQhnAAhJhKgAALAAIBkBkIhkhkIBkhjIhkBjgAhYBkIBjhkIhjhjIBjBjg");
	this.shape_2.setTransform(-1.1,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-26.1,-25,50.1,53.8);


// stage content:
(lib.Baedar = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		// This thing should be Global, thx
		
		var socket = io();
		window.socket = socket;
		this.curStats = {};
		
		var username = window.location.search.substr(1);
		if (username == '') {
			username = 'dummy';
		}
		
		socket.emit('phone connect', username);
		
		function randomizeStats() {
			var optionIndex = Math.floor(window.options.length * Math.random())
			var option = window.options[optionIndex];
			
			this.photo.gotoAndStop(optionIndex);
			this.curStats = option.stats;
			this.baeDescription.text = option.name + "\n" + option.text;
		}
		this.randomizeStats = randomizeStats.bind(this);
		
		function pickRandom(list) {
			return list[Math.floor(list.length * Math.random())];
		}
		
		function randomRange(min, max) {
			return (max - min) * Math.random() + min;
		}
		
		function sayNo() {
			this.noButton.play();
			this.randomizeStats();
		}
		
		function sayYes() {
			this.yesButton.play();
			socket.emit('set stat', this.curStats);
			this.randomizeStats();
		}
		
		this.noButton.on('click', sayNo.bind(this));
		this.yesButton.on('click', sayYes.bind(this));
		this.randomizeStats();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(1));

	// Border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#8DB3E8").ss(4,1,1).p("Ax4+7MAjxAAAQBVAAAABTMAAAA7SQAABShVAAMgjxAAAQhVAAAAhSMAAAg7SQAAhTBVAAg");
	this.shape.setTransform(125.1,200);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgXvAiiMAAAhFDMAvfAAAMAAABFDgAzh9yMAAAA7RQAABTBWAAMAjwAAAQBVAAAAhTMAAAg7RQAAhThVAAMgjwAAAQhWAAAABTg");
	this.shape_1.setTransform(127,201);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	// Buttons
	this.yesButton = new lib.Yes();
	this.yesButton.name = "yesButton";
	this.yesButton.parent = this;
	this.yesButton.setTransform(210,250);

	this.noButton = new lib.no();
	this.noButton.name = "noButton";
	this.noButton.parent = this;
	this.noButton.setTransform(40,250);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.noButton},{t:this.yesButton}]}).wait(1));

	// Text
	this.baeDescription = new cjs.Text("Hello", "16px 'Helvetica'");
	this.baeDescription.name = "baeDescription";
	this.baeDescription.lineHeight = 21;
	this.baeDescription.lineWidth = 222;
	this.baeDescription.parent = this;
	this.baeDescription.setTransform(14.8,288.3);

	this.timeline.addTween(cjs.Tween.get(this.baeDescription).wait(1));

	// TextBg
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#8DB3E8").ss(4,1,1).p("A0TAAMAonAAA");
	this.shape_2.setTransform(125,249.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("A0TMHIAA4NMAonAAAIAAYNg");
	this.shape_3.setTransform(125,327.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_3},{t:this.shape_2}]}).wait(1));

	// Photo
	this.photo = new lib.Photos();
	this.photo.name = "photo";
	this.photo.parent = this;
	this.photo.setTransform(125,125);

	this.timeline.addTween(cjs.Tween.get(this.photo).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(100.1,180.1,304,442);
// library properties:
lib.properties = {
	id: '5769986BB74349668603016E48E17B41',
	width: 250,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"sounds/nopewav.mp3", id:"nopewav"},
		{src:"sounds/yeswav.mp3", id:"yeswav"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['5769986BB74349668603016E48E17B41'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;